package com.lizhihui.camile.app.mybatis.client;

import com.lizhihui.camile.app.mybatis.entity.CityBuilding;
import com.lizhihui.camile.app.mybatis.entity.CityBuildingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CityBuildingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    int countByExample(CityBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    int deleteByExample(CityBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String building);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    int insert(CityBuilding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    int insertSelective(CityBuilding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    List<CityBuilding> selectByExampleWithRowbounds(CityBuildingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    List<CityBuilding> selectByExample(CityBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    CityBuilding selectByPrimaryKey(String building);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CityBuilding record, @Param("example") CityBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CityBuilding record, @Param("example") CityBuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CityBuilding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AAM_CITY_BUILDING
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CityBuilding record);
}