package com.lizhihui.camile.app.mybatis.client;

import com.lizhihui.camile.app.basic.dao.Mapper;
import com.lizhihui.camile.app.mybatis.entity.User;
import com.lizhihui.camile.app.mybatis.entity.UserCondition;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface UserMapper extends Mapper<User, UserCondition> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    List<User> selectByExampleWithRowbounds(UserCondition example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    List<User> selectByExample(UserCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
}